{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","level":"warn","timestamp":"2018-05-17T03:04:49.431Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","level":"warn","timestamp":"2018-05-17T03:04:49.435Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","level":"warn","timestamp":"2018-05-17T03:04:49.436Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","level":"warn","timestamp":"2018-05-17T03:05:02.523Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","level":"warn","timestamp":"2018-05-17T03:05:02.527Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\Taike\\Documents\\Angular\\chatroom-app\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","level":"warn","timestamp":"2018-05-17T03:05:02.528Z"}
